# Replace `node:14` with `node:14-alpine`
FROM node:14-alpine

ARG user="node"
ARG appdir="/home/node/app"

RUN mkdir -p ${appdir} && chown -R ${user} ${appdir}
WORKDIR ${appdir}
USER ${user}

COPY --chown=${user} package.json package-lock.json ./
RUN npm install

COPY --chown=${user} . .

CMD [ "npm", "start" ]